### ISSUE TITLE
FeedReelsTrayRequest not working well

### ISSUE THREAD

**Issue by mokhtarabadi** [instagram4j/instagram4j#504] opened 2020-10-04 09:23 UTC
## Issue Template Requirements

Issue must be of the specified template and follow these requirements or it will be ignored. 
- Please do not post screenshots of code output
- Wrap code in a codeblock
- exhibiting spam behavior or "evil" behavior will have the issue ignored
- Please make sure your issue hasn't been asked before
- Please complete the checklist below (mark boxes [ ] with [x])

---

### Pre-Checklist

I made sure...
- [ x ] I read the README.md
- [ x ] I looked over the examples and wiki
- [ x ] my issue hasn't been asked or solved before

---

### Describe the bug

Please provide a concise description of your bug and relevant code.

### How to reproduce

1. Specify steps to reproduce
```java
public static void main(String[] args) {
    //test
        IGClient igClient = IGHelper.getInstance().getIGClient(PreferencesHelper.getInstance().getCurrentAccount());
        FeedReelsTrayRequest feedReelsTrayRequest = new FeedReelsTrayRequest();

        feedReelsTrayRequest.execute(igClient).whenComplete((feedReelsTrayResponse, throwable) -> {
            if (throwable != null) {
                throwable.printStackTrace();
            } else {
                for (Reel reel : feedReelsTrayResponse.getTray()) {
                    for (ReelMedia item : reel.getItems()) {
                        log.info("child item type is " + item.getMedia_type());
                    }
                }
            }
        });
        //test
}
```
### Expected behavior

Sometimes reel.getItems() is null or the output of "child item type is" is less than real

### Actual behavior

I debug full response from the Instagram API server, the problem I think is parsing JSON, because the raw JSON response has all items

**Comment by mokhtarabadi** [comment] 2020-10-05 06:37
also I check with conditions 
`java
 feedReelsTrayResponse.getTray() != null and reel.getItems() != null
`

**Comment by jvogit** [comment] 2020-10-15 22:58
Could you provide sample json response and point out the problem?

**Comment by mokhtarabadi** [comment] 2020-10-18 10:50
Basically, how can get recent stories of all my followings?
I mean the top view on the main screen of the Instagram Android app

**Comment by jvogit** [comment] 2020-10-19 09:55
FeedReelsTrayRequest should provide that. If you want to mark a story as seen then [MediaSeenRequest](https://github.com/instagram4j/instagram4j/blob/develop/src/main/java/com/github/instagram4j/instagram4j/requests/media/MediaSeenRequest.java) is needed.

You mention a problem with the request regarding json. If you could provide examples with json output, itd be appreciated since I'm unable to reproduce your bug.

**Comment by mokhtarabadi** [comment] 2020-10-19 10:55
Oh, I think this issue is wrong, I check again the full raw response from Instagram, only the first "tray" item have "items" property and others didn't have it, but have media_ids, (I thought all items must have items property so created this issue)

now, how can I get info for media_id, currently I using MediaInfoRequest, but only accept one media_id per request, can I retrieve information for multiple media_id?

**Comment by jvogit** [comment] 2020-10-19 18:53
I don't think there is a request to select multiple media_ids or at least I didn't find one.

Closing the issue since it seems resolved.

**Closed by jvogit** 2020-10-19 18:53 UTC
Labels: bug

**Comment by bloworlf** [comment] 2022-03-06 21:49
I just came across this issue. All Reels from FeedReelsTrayRequest/Response have media_ids, but items is null as shown in the screenshot

<img width="434" alt="image" src="https://user-images.githubusercontent.com/39887108/156943438-dfbc4083-f96b-4484-9323-2f95195a0532.png">

Is there a way to fix this? Or is there a request to get a story by its ID?

**Comment by ErrorxCode** [comment] 2022-03-07 01:47
What Did you except there ?

**Comment by bloworlf** [comment] 2022-03-07 01:57
I'm trying to get the list of stories usually shown at the top of instagram feed app.

I get response from FeedReelsTrayRequest, but every time, when I iterate through the list of Reel, reel.getItems() has data only for the first one.

I want to be able to show a thumbnail of the last story for each user when displaying all of the stories

Here's what I managed to do:

![WhatsApp Image 2022-03-06 at 16 52 12](https://user-images.githubusercontent.com/39887108/156954718-ad8ce54b-2d42-470e-8e26-d6a62bfe92ce.jpeg)


Thank you for all of this by the way. This API is super super useful.

**Comment by ErrorxCode** [comment] 2022-03-07 02:01
Actually it is a paging request. Means that you have to get next cursor
from the previous request and have to request with that new cursor
everytime until the getNextCursor() method returns null.

**Comment by bloworlf** [comment] 2022-03-07 02:21
I'm sorry, but I cannot find any method to set pagination data to the request.

I used
`FeedReelsTrayResponse response = client.actions().story().tray().join();`
from
[FeedReelsTrayFeedRequestTest](https://github.com/instagram4j/instagram4j/blob/master/src/examples/java/feed/FeedReelsTrayFeedRequestTest.java)

And used it like that
`FeedReelsTrayRequest req = new FeedReelsTrayRequest();`
`FeedReelsTrayResponse res = req.execute(client).join();`
`return res.getTray();`
Which returns a `List<Reel>`

And then
`for(Reel reel : listReel){`
`List<ReelMedia> listMedia = reel.getItems(); // <-- always returns null starting from 2nd element`
`}`

**Comment by ErrorxCode** [comment] 2022-03-07 02:26
Doesn't the constructor of the request takes a string as an argument ?

**Comment by bloworlf** [comment] 2022-03-07 02:28
<img width="390" alt="image" src="https://user-images.githubusercontent.com/39887108/156957420-0c421f36-a478-48c3-be53-a20347dd79a4.png">

Not this class.

**Comment by ErrorxCode** [comment] 2022-03-07 09:07
> <img alt="image" width="390" src="https://user-images.githubusercontent.com/39887108/156957420-0c421f36-a478-48c3-be53-a20347dd79a4.png">
> 
> Not this class.

Let the owner see your problem. By the way.... you can use the [EasyInsta](https://github.com/ErrorxCode/EasyInsta) library if it's enough for you.

**Comment by bloworlf** [comment] 2022-03-07 14:07
Naaa, this one is better. It is a little complicated since I don't use the functions exactly as they are in the examples provided, but it's better. This is not really an issue: I can still display the list of user who have posted stories instead of also showing the last posted story of those users.
I want to create an app with a maximum of functionalities where everything is downloadable. Right now, I just need to find out how to download live broadcasts and it will be like 60% complete.
