### ISSUE TITLE
connection time out when trying to invoke instagram.login()

### ISSUE THREAD

**Issue by fxpal-git** [instagram4j/instagram4j#30] opened 2017-06-23 04:24 UTC
When trying to login i am getting "connection time out", when running from a standalone application which is not behind any proxy network. I have pasted the stack trace as shown below. 

`2017-06-23 09:20:58 [main] INFO  org.brunocvcunha.instagram4j.Instagram4j  - Sending request: org.brunocvcunha.instagram4j.requests.internal.InstagramFetchHeadersRequest
2017-06-23 09:20:58 INFO  Instagram4j:194 - Sending request: org.brunocvcunha.instagram4j.requests.internal.InstagramFetchHeadersRequest
java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:532)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:409)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:882)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.brunocvcunha.instagram4j.requests.InstagramGetRequest.execute(InstagramGetRequest.java:48)
	at org.brunocvcunha.instagram4j.Instagram4j.sendRequest(Instagram4j.java:202)
	at org.brunocvcunha.instagram4j.Instagram4j.getOrFetchCsrf(Instagram4j.java:175)
	at org.brunocvcunha.instagram4j.Instagram4j.login(Instagram4j.java:139)
	at com.tiaa.TestInstagram.main(TestInstagram.java:16)
`

**Comment by brunocvcunha** [comment] 2017-06-25 19:18
Couldn't reproduce.
Does it happen every time? 

Can you reach i.instagram.com through port 443? `telnet i.instagram.com 443`

**Comment by fxpal-git** [comment] 2017-07-07 12:43
Sorry for delayed response. I was able to telnet to i.instagram.com, but getting "connection time out" and below is the stack trace.
`java.net.ConnectException: Connection timed out: connect
    at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
    at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
    at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
    at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
    at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
    at java.net.PlainSocketImpl.connect(Unknown Source)
    at java.net.SocksSocketImpl.connect(Unknown Source)
    at java.net.Socket.connect(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
    at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:542)
    at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:412)
    at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:179)
    at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:328)
    at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:612)
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:447)
    at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
    at com.tiaa.instagram.requests.InstagramGetRequest.execute(InstagramGetRequest.java:48)
    at com.tiaa.instagram.Instagram.sendRequest(Instagram.java:232)
    at com.tiaa.instagram.Instagram.getOrFetchCsrf(Instagram.java:205)
    at com.tiaa.instagram.Instagram.login(Instagram.java:169)`

I tried to set SO_TIMEOUT and CONNECTION_TIMEOUT using HttpConnectionParams, but still getting the same issue. Please do let me know your thoughts as how to have this resolved?

**Comment by krismorte** [comment] 2017-08-25 16:40
I'm under a proxy server and I have the same error. I try test telnet port and fail
![telnet](https://user-images.githubusercontent.com/15660341/29723412-e21ee37c-899a-11e7-81ea-8cef74fab3c9.jpg)

**Comment by jvogit** [comment] 2020-08-05 00:13
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.

**Closed by jvogit** 2020-08-05 00:13 UTC
