### ISSUE TITLE
Could not initialize class org.bytedeco.javacpp.avformat$AVFormatContext

### ISSUE THREAD

**Issue by AleTassi** [instagram4j/instagram4j#345] opened 2019-07-14 13:01 UTC
Hi,

with version 1.11, trying to upload a video i get this error:
``
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avformat$AVFormatContext
	at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:468) ~[javacv-1.3.1.jar:1.3.1]
	at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:462) ~[javacv-1.3.1.jar:1.3.1]
	at org.brunocvcunha.instagram4j.requests.InstagramUploadVideoRequest.configureThumbnail(InstagramUploadVideoRequest.java:131) ~[instagram4j-1.11.jar:na]
	at org.brunocvcunha.instagram4j.requests.InstagramUploadVideoRequest.execute(InstagramUploadVideoRequest.java:109) ~[instagram4j-1.11.jar:na]
	at org.brunocvcunha.instagram4j.requests.InstagramUploadVideoRequest.execute(InstagramUploadVideoRequest.java:52) ~[instagram4j-1.11.jar:na]
	at org.brunocvcunha.instagram4j.Instagram4j.sendRequest(Instagram4j.java:281) ~[instagram4j-1.11.jar:na]
``

**Comment by DanielePancottini** [comment] 2019-07-14 16:30
Hi @AleTassi the problem is already solved with a PR, you have only to wait next release of this API 👍

**Comment by einherjarr** [comment] 2019-10-30 11:16
you are missing java cpp libraries, just add maven to your project and let it install what is necessary, solved this problem like that

**Comment by jvogit** [comment] 2020-08-05 00:38
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.

**Closed by jvogit** 2020-08-05 00:38 UTC
