### ISSUE TITLE
Following list return null

### ISSUE THREAD

**Issue by mehmaj** [instagram4j/instagram4j#326] opened 2019-05-28 09:58 UTC
InstagramGetUserFollowersResult Following = instagram.sendRequest(new InstagramGetUserFollowingRequest(instagram.getUserId()));
            List users = Following.getUsers();

I used this for 4 different accounts
everything is working like a charm but InstagramGetUserFollowingRequest
what is the problem?
the response status is 200 OK 
<img width="336" alt="Screen Shot 2019-05-28 at 2 26 26 PM" src="https://user-images.githubusercontent.com/31012967/58469428-bd057c00-8154-11e9-83d3-7b56036a27d5.png">

**Comment by jemand771** [comment] 2019-05-28 18:32
Sadly, I can only give you the "standard" response: It works on my machine. Your exact code gives me a list of all users that follow me.
Which version of instagram4j are you using? I've tested it with the latest snapshot locally. Are there actually users that follow the used accounts? Also, double check that the login works and the user id you use is correct.

One final hint for the future: please format your code with markdown, either using the respective button or by surrounding it with `` manually so it looks `like this` (or three on each side to produce a long code block) [markdown cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code)

**Comment by DanielePancottini** [comment] 2019-05-28 18:52
Hi @mehmaj, maybe the problem is the parameter of the list `users`, try to declare users list with the following code:
`List<InstagramUserSummary> users = Following.getUsers();`

In case of this should not work, try with following code:

```
instagram.setup();
instagram.login();
			
InstagramSearchUsernameResult userResult = instagram.sendRequest(new InstagramSearchUsernameRequest(instagram.getUsername()));
			
InstagramGetUserFollowersResult userFollowers = instagram.sendRequest(new InstagramGetUserFollowingRequest(userResult.getUser().getPk()));

List<InstagramUserSummary> users = userFollowers.getUsers();
```

**Comment by jvogit** [comment] 2020-08-05 00:34
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.

**Closed by jvogit** 2020-08-05 00:34 UTC
